### ISSUE TITLE
abelectronicsadcpi doing blocking calls at custom_components/abelectronicsadcpi/ADCPi.py

### ISSUE THREAD

**Issue by timnis** [abelectronicsuk/abelectronics-home-assistant-custom-components#3]
Hi,

Just tested ADC Pi v2.2 with HomeAssistant core-2022.3.8 (on  Home Assistant Operating System). HW is Raspberry Pi 4 2GB.
Installation instruction were good and no issued there.

But now on  log there following warning and all system feels sluggish. Any ideas how to fix it?
`2022-03-29 20:38:16 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for abelectronicsadcpi doing blocking calls at custom_components/abelectronicsadcpi/ADCPi.py, line 276: time.sleep(0.00001)  # sleep for 10 microseconds`

**Comment by abelectronicsuk** [comment]
Hi

I have made some changes to the ADCPi.py and sensor.py files to improve the performance and stop the warnings in the error log.  Please can you try the new version and see if it stops your system from feeling sluggish?

**Comment by timnis** [comment]
Hi,
Just installed new version and now no errors and no more sluggish feelings :)
This resolved issue and can be closed.
