### ISSUE TITLE
Demo UI Cards - where to integrate this on HA

### ISSUE THREAD

**Issue by MkLHX** [abelectronicsuk/abelectronics-home-assistant-custom-components#4]
Hello, 
I'm looking for documentation on the Demo UI cards integration on Home Assistant

https://github.com/abelectronicsuk/abelectronics-home-assistant-custom-components/tree/master/abelectronicsiopi#demo-ui-cards

Can you, please, tel me more where integrate the yaml directives to see IO pi plus on HA GUI?

**Comment by abelectronicsuk** [comment]
Hello

The Demo UI card used in our integration tutorial is a Home Assistant Entities Card. You can find documentation on using the Entities Card on Home Assistants website at [https://www.home-assistant.io/dashboards/entities/](https://www.home-assistant.io/dashboards/entities/)

**Comment by MkLHX** [comment]
Hi thanks for your reply,

So if i understand, i have to declare entities directives in configuration.yml like this?

```

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


switch:
  - platform: abelectronicsiopi
    i2c_address: 0x20
    invert_logic: false
    pins:
      1: Pin 1 Switch
      2: Pin 2 Switch
      3: Pin 3 Switch
      4: Pin 4 Switch
      5: Pin 5 Switch
      6: Pin 6 Switch
      7: Pin 7 Switch
      8: Pin 8 Switch
      9: Pin 9 Switch
      10: Pin 10 Switch
      11: Pin 11 Switch
      12: Pin 12 Switch
      13: Pin 13 Switch
      14: Pin 14 Switch
      15: Pin 15 Switch
      16: Pin 16 Switch
type: entities
title: IO Pi Outputs
entities:
  - entity: switch.pin_1_switch
  - entity: switch.pin_2_switch
  - entity: switch.pin_3_switch
  - entity: switch.pin_4_switch
  - entity: switch.pin_5_switch
  - entity: switch.pin_6_switch
  - entity: switch.pin_7_switch
  - entity: switch.pin_8_switch
  - entity: switch.pin_9_switch
  - entity: switch.pin_10_switch
  - entity: switch.pin_11_switch
  - entity: switch.pin_12_switch
  - entity: switch.pin_13_switch
  - entity: switch.pin_14_switch
  - entity: switch.pin_15_switch
  - entity: switch.pin_16_switch
```

If yes, i missed something because when i run check configuration i get some errors:
![image](https://github.com/abelectronicsuk/abelectronics-home-assistant-custom-components/assets/17542841/4e9c743a-9796-40cc-afc0-29c419139337)

**Comment by abelectronicsuk** [comment]
The entities part will need to go in an Entities card on the dashboard.

I have uploaded a YouTube video to show how this is done. [https://www.youtube.com/watch?v=vEbRBNdHHMY](https://www.youtube.com/watch?v=vEbRBNdHHMY)

**Comment by MkLHX** [comment]
Thank you so much!
I understand now.

But I'm still encountering an error:

I've copy/paste yaml configuration from readme:
```
binary_sensor:
  - platform: abelectronicsiopi
    i2c_address: 0x20
    scan_interval: 1
    invert_logic: false
    pull_mode: true
    pins:
      1: Pin 1 Sensor
      2: Pin 2 Sensor
      3: Pin 3 Sensor
      4: Pin 4 Sensor
      5: Pin 5 Sensor
      6: Pin 6 Sensor
      7: Pin 7 Sensor
      8: Pin 8 Sensor
      9: Pin 9 Sensor
      10: Pin 10 Sensor
      11: Pin 11 Sensor
      12: Pin 12 Sensor
      13: Pin 13 Sensor
      14: Pin 14 Sensor
      15: Pin 15 Sensor
      16: Pin 16 Sensor
switch:
  - platform: abelectronicsiopi
    i2c_address: 0x21
    invert_logic: false
    pins:
      1: Pin 1 Switch
      2: Pin 2 Switch
      3: Pin 3 Switch
      4: Pin 4 Switch
      5: Pin 5 Switch
      6: Pin 6 Switch
      7: Pin 7 Switch
      8: Pin 8 Switch
      9: Pin 9 Switch
      10: Pin 10 Switch
      11: Pin 11 Switch
      12: Pin 12 Switch
      13: Pin 13 Switch
      14: Pin 14 Switch
      15: Pin 15 Switch
      16: Pin 16 Switch
```

And then create 2 cards:

one for inputs
![image](https://github.com/abelectronicsuk/abelectronics-home-assistant-custom-components/assets/17542841/4a7f43f8-ce17-4f15-abfe-6022db5e885c)

and the second for outputs:
![image](https://github.com/abelectronicsuk/abelectronics-home-assistant-custom-components/assets/17542841/321f509e-f0b9-4813-b485-db29578afa46)

The errors refer to a missing arguments inside configuration.yaml

Did I miss something?

**Comment by abelectronicsuk** [comment]
This is the contents of the configuration on my Home Assistant install which I used to make the video.

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor:
  - platform: abelectronicsiopi
    i2c_address: 0x20
    scan_interval: 1
    invert_logic: false
    pull_mode: true
    pins:
      1: Pin 1 Sensor
      2: Pin 2 Sensor
      3: Pin 3 Sensor
      4: Pin 4 Sensor
      5: Pin 5 Sensor
      6: Pin 6 Sensor
      7: Pin 7 Sensor
      8: Pin 8 Sensor
      9: Pin 9 Sensor
      10: Pin 10 Sensor
      11: Pin 11 Sensor
      12: Pin 12 Sensor
      13: Pin 13 Sensor
      14: Pin 14 Sensor
      15: Pin 15 Sensor
      16: Pin 16 Sensor

switch:
  - platform: abelectronicsiopi
    i2c_address: 0x21
    invert_logic: false
    pins:
      1: Pin 1 Switch
      2: Pin 2 Switch
      3: Pin 3 Switch  
      4: Pin 4 Switch
      5: Pin 5 Switch
      6: Pin 6 Switch
      7: Pin 7 Switch
      8: Pin 8 Switch
      9: Pin 9 Switch
      10: Pin 10 Switch
      11: Pin 11 Switch
      12: Pin 12 Switch
      13: Pin 13 Switch
      14: Pin 14 Switch
      15: Pin 15 Switch
      16: Pin 16 Switch
```
Have you copied the [abelectronicsiopi](https://github.com/abelectronicsuk/abelectronics-home-assistant-custom-components/tree/master/abelectronicsiopi/custom_components/abelectronicsiopi) directory and its contents into the custom_components directory?

Here is a screenshot of the Visual Studio Code extension in my Home Assistant install showing the directory structure for the abelectronicsiopi custom component.
<img width="1678" alt="Screenshot 2024-02-01 at 15 58 42" src="https://github.com/abelectronicsuk/abelectronics-home-assistant-custom-components/assets/3626089/9502b77d-8b67-47c6-8f9a-0637e1d4d203">

**Comment by MkLHX** [comment]
Hello @abelectronicsuk 

Yes I've installed the abelectronicsiopi inside custom_components.

![image](https://github.com/abelectronicsuk/abelectronics-home-assistant-custom-components/assets/17542841/50d158e0-58cf-4865-bbb8-cacc3e43cdae)

**Comment by abelectronicsuk** [comment]
The problem could be that Home Assistant is having trouble communicating with the IO Pi Plus. Are the I2C addresses on the IO Pi Plus still set to their default positions of 0x20 and 0x21? Do you have any other devices plugged into the Raspberry Pi that are using the same I2C addresses or using the I2C bus?

**Comment by MkLHX** [comment]
Hum currently, iopiplus isn't connected I'm just preparing the HA configuration for migration from jeedom to HA.

So the HA instance is running on a VM until I'll transfert the backup to the new instance on RPI.

So if yaml configurations are good I just have to see in the future the behavior of the abelectronicsiopi integration.

**Comment by abelectronicsuk** [comment]
If the IO Pi Plus is not connected that would explain the error you are getting. Hopefully, once you connect it to your Raspberry Pi the abelectronicsiopi integration will begin working.

**Comment by MkLHX** [comment]
Hi @abelectronicsuk i'm trying to migrate from jeedom to home assistant.
I'm encountered an issue during the activation of i2c and dowload the python deps to run io pi plus.
can you give me an advice to manage it?
trying ssh but no /boot/config.txt accessible

**Comment by abelectronicsuk** [comment]
You may need to mount the SD card on a different computer to access the config.txt file as the Home Assistant OS runs inside a docker container so you don't have easy access to the root OS.

We have a tutorial on our website that goes through the steps needed to  [activate I2C on Home Assistant OS.](https://www.abelectronics.co.uk/kb/article/1116/using-i2c-devices-with-home-assistant-on-the-raspberry-pi)

**Comment by MkLHX** [comment]
Ok thx, i'll follow the tutorial and hope i'll manage to use the board ;-)

**Comment by MkLHX** [comment]
ok just for following and people looking for the same thing.

I manage to command iopiplus board using this plugin:
[HassOS I2C Configurator](https://github.com/adamoutler/HassOSConfigurator)

And following the steps on the [documentation](https://www.abelectronics.co.uk/kb/article/1116/using-i2c-devices-with-home-assistant-on-the-raspberry-pi)

The problem is when you install HA as a raspberry pi os you haven't any access to the os it self because the system run a docker container without root access on the host's os.
So you can't access to the raspberry side.

Just read the doc and stay patient ;-) it's will work.

Thank you for the help!
